version: '3.8'

services:
  # order-service:
  #   build: ./order-service
  #   ports:
  #     - "5003:5003"

  order-db-mysql:
    image: mysql:8.4.0
    restart: always
    environment:
      - MYSQL_DATABASE=restaurant_system_order
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3309:3306"
    volumes:
      - order-db-data:/var/lib/mysql

  # payment-service:
  #   build: ./payment-service
  #   ports:
  #     - "5004:5004"

  payment-db-mysql:
    image: mysql:8.4.0
    restart: always
    environment:
      - MYSQL_DATABASE=restaurant_system_payment
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3310:3306"
    volumes:
      - payment-db-data:/var/lib/mysql

volumes:
  order-db-data:
  payment-db-data:
